### ISSUE TITLE
[Requirement] TLS communication for cloud-hosted HPS

### ISSUE THREAD

**Issue by Spartee** [NVIDIA-Merlin/HugeCTR#363] opened 2022-11-02 20:07 UTC
### Description
 It would be great if TLS communication were added as an option to client initialization in [redis_backend.cpp](https://github.com/NVIDIA-Merlin/HugeCTR/blob/6177889df69258919533c0f5658492332400b8eb/HugeCTR/src/hps/redis_backend.cpp#L53)

Adding a TLS option would secure communication between the HPS and HugeCTR when hosting the CPU cache component of the HPS separate (not the same server) from the triton server instance.

### Benefits

Adding TLS communication would further a cloud-hosted HPS which has the following benefits:

- Security: only option for security today is basic ACL auth. TLS would improve this.
- Cost: this would be specifically advantageous for users looking to utilize cheap CPU cloud instances with high memory for the embedding storage.
- Infrastructure simplicity: 
   - Many of the cloud hosted versions redis (i.e. Redis Enterprise) are compatible with existing redis client and very easy to setup, manage, and scale. 
   - Expanded storage options: Some cloud offerings offer flash storage which replaces the need to setup per tritonserver or NFS rocksdb further decreasing amount of setup in order to put HPS into production.

### Implementation
Add parameters to the redis client intiialization to allow the passing of key and pem files for TLS communication. the dependency used for Redis communication already has support for this. See an example [here](https://github.com/sewenew/redis-plus-plus#tlsssl-support).

Keep in mind, This will require a build flag for Redis-plus-plus and openssl to be available, but I don't believe that to be a preventative hurdle here as this is relatively standard practice for secure communication.

### Alternatives
Only offer ACL auth forgoing the above benefits outlined for cloud hosted embedding storage.

### Additional context
Adding unix socket support here as well might be a good idea since it's touching the same area of the codebase. This would improve performance in co-located settings when that is preferred. I can write up a separate ticket for this though.

**Comment by zehuanw** [comment] 2022-11-02 23:00
Thank you for the feature requirement and detailed description! We will analyze and update to you soon.

**Comment by bashimao** [comment] 2022-11-03 00:07
@zehuanw This is content-wise a duplicate of !639 on GitLab , but way more detailed. Thank you @Spartee .

**Comment by bashimao** [comment] 2022-11-03 06:34
Performance impact is there and measurable, but I assume that people who want SSL are willing to accept that. See also: 
https://github.com/redis/redis/issues/7595

**Comment by bashimao** [comment] 2022-11-03 06:36
Server-side configuration: https://redis.io/docs/management/security/encryption/

**Comment by bashimao** [comment] 2022-11-03 06:46
@minseokl @zehuanw Btw. this is a good example where moving dependency configuration back from Merlin / `docker` into the HugeCTR repo  / `cmake` as a `third_party` dependency is really helpful. In the old build system, we would have had to propose a change to the Merlin project and wait for the change to become available. Definitely a win.

**Comment by bashimao** [comment] 2023-01-03 06:23
@zehuanw Will already be addressed in `v22.12`.

**Closed** 2023-01-17 09:26 UTC
Labels: fea::functional, requirement
