### ISSUE TITLE
[Question] Why gpu_cache's capacity is larger than embedding table, but the hit rate is not one hundred percent?

### ISSUE THREAD

**Issue by marsmiao** [NVIDIA-Merlin/HugeCTR#278] opened 2021-12-05 14:08 UTC
Try different cache capacity and evaluate the hit rate. If the capacity of embedding cache can be larger than actual embedding footprint, the hit rate can be as high as 99%+.

Can anybody explain this? Thank you.

**Comment by yingcanw** [comment] 2021-12-06 03:24
@marsmiao 
Thank you for your feedback. The 100% hit rate you mentioned is theoretically achievable, but it is almost impossible in actual industrial use cases. First, the training data cannot fully cover real-time inference features, so there must be missing features in the embedded table for inference. Second, even for online training, there is still a delay in the update of the embedding cache, which will also cause the missing features.
Therefore, the description here（**as high as 99%+**） can be understood as an infinite approximation to 100%.

**Comment by marsmiao** [comment] 2021-12-06 03:47
> 

Thanks a lot for you explaination, but in my case, if I can ensure that the feature keys are stored totally before, the inference hit rate will always be 100%? or will be not.

**Comment by marsmiao** [comment] 2021-12-06 09:39
@yingcanw after some quick test, I found that because of nv_gpu_cache's lru cache, the num_slots could not be totally used, is there something to fix this?

**Comment by HWZealot** [comment] 2021-12-07 08:46
@marsmiao Hi, if you can make sure that all the embeddings you need(i.e. embedding footprint) are stored inside the cache, the hit rate of cause will be 100%.
The real reason for "If the capacity of embedding cache can be larger than actual embedding footprint, the hit rate can be as high as 99%+" is not because the LRU replacement algorithm. The **Replace** API of our cache will try to find any available empty slot in the cache first. If there is a empty slot, than the embedding key will be inserted into this slot and the LRU replacement algorithm will not be used at all. The real reason is that this GPU embedding cache, just as any other HW implemented cache, has a concept called **set associative**. A embedding key can only be mapped to 1 cache set(which is 64 slots by default in our code, you can change it) and it has to be placed in one of the slots in this set. So, the available slots for a certain embedding key is only 64 not the cache capacity. If the cache is heavily load-imbalanced between cache sets(i.e. some cache set are nearly full while others are nearly empty) then many keys will be missed not because the cache is not big enough(there are still empty slots in the cache), but becasue the cache sets for the embedding keys are full. This is called **conflict miss** from cache design perspective. 
For example, if your cache has 640 slots in total(10 cache sets each 64 slots), now your embedding footprint is 640 keys without duplication, . If your cache is perfectly balanced(i.e. map exactly 64 keys to each cache set), you can store all 640 keys inside the cache, and your hit rate will be 100% for sure. However, any imbalance will cause the hit rate to be lower than 100%. That's why "If the capacity of embedding cache can be larger than actual embedding footprint, the hit rate can be as high as 99%+" but not guarantee to be 100%.
We have addressed this issue by using a very random hash fuction to map embedding keys to different cache set. So, non-duplicated keys are very very unlikely to be mapped to the same cache set unless the hash function is been attacked. This will help to make the cache to be highly balanced, but can't guarantee a perfectly balanced cache(for example, you may end up with a cache set with 63 keys and another with 61 keys, the difference is highly unlikely to be large). If your cache's capacity is 1000 and your embedding footprint is 900, you are very likely to reach 100% hit rate. But if your embedding footprint is 999, then you may get a hit rate less than 100% thanks to this **conflict miss** issue.
For solutions, have larger cache set will help. In the extreme scenario, if your cache set has the same size as your cache capacity, you will have only 1 cache set per cache(i.e. a fully associative cache) and this **conflict miss** issue is completely gone. You will definitely get 100% hit rate if "the capacity of embedding cache can be larger than actual embedding footprint". But, the larger the cache set, the slower the searching process, so here is a hit rate vs cache performance trade-off.
Also, if you really need to guarantee 100% hit rate when "the capacity of embedding cache can be larger than actual embedding footprint", you can use a data structure such as a hash table or even a linear array which don't depend on probability instead of a cache.
Offen, this few percentages of miss rate caused by **conflict miss** issue won't have much impact on performance. If the hit rate is high enough, say 98%, we can just ignore the rest 2% missing keys and assign some default embedding vector to them and go to the rest of the inference pipeline. The accuracy of the inference will not be affected by this 2% missing embeddings.

Hope this would help.

**Comment by KingsleyLiu-NV** [comment] 2021-12-07 09:17
@marsmiao Could you please provide your configurations for inference? For example:
```
inference_params = InferenceParams(model_name = "dcn",
                                max_batchsize = 1024,
                                hit_rate_threshold = 1.0,
                                dense_model_file = "./dcn_dense_2000.model",
                                sparse_model_files = ["./dcn0_sparse_2000.model"],
                                device_id = 0,
                                use_gpu_embedding_cache = False,
                                cache_size_percentage = 1.0,
                                i64_input_key = False,
                                use_mixed_precision = False,
                                use_cuda_graph = True)
```
and share which container is being used or on which branch you are building from source.

**Comment by marsmiao** [comment] 2021-12-07 12:12
> @marsmiao Hi, if you can make sure that all the embeddings you need(i.e. embedding footprint) are stored inside the cache, the hit rate of cause will be 100%. The real reason for "If the capacity of embedding cache can be larger than actual embedding footprint, the hit rate can be as high as 99%+" is not because the LRU replacement algorithm. The **Replace** API of our cache will try to find any available empty slot in the cache first. If there is a empty slot, than the embedding key will be inserted into this slot and the LRU replacement algorithm will not be used at all. The real reason is that this GPU embedding cache, just as any other HW implemented cache, has a concept called **set associative**. A embedding key can only be mapped to 1 cache set(which is 64 slots by default in our code, you can change it) and it has to be placed in one of the slots in this set. So, the available slots for a certain embedding key is only 64 not the cache capacity. If the cache is heavily load-imbalanced between cache sets(i.e. some cache set are nearly full while others are nearly empty) then many keys will be missed not because the cache is not big enough(there are still empty slots in the cache), but becasue the cache sets for the embedding keys are full. This is called **conflict miss** from cache design perspective. For example, if your cache has 640 slots in total(10 cache sets each 64 slots), now your embedding footprint is 640 keys without duplication. If your cache is perfectly balanced(i.e. map exactly 64 keys to each cache set), you can store all 640 keys inside the cache, and your hit rate will be 100% for sure. However, any imbalance will cause the hit rate to be lower than 100%. That's why "If the capacity of embedding cache can be larger than actual embedding footprint, the hit rate can be as high as 99%+" but not guarantee to be 100%. We have addressed this issue by using a very random hash fuction to map embedding keys to different cache set. So, non-duplicated keys are very very unlikely to be mapped to the same cache set unless the hash function is been attacked. This will help to make the cache to be highly balanced, but can't guarantee a perfectly balanced cache(for example, you may end up with a cache set with 63 keys and another with 61 keys, the difference is highly unlikely to be large). If your cache's capacity is 1000 and your embedding footprint is 900, you are very likely to reach 100% hit rate. But if your embedding footprint is 999, then you may get a hit rate less than 100% thanks to this **conflict miss** issue. For solutions, have larger cache set will help. In the extreme scenario, if your cache set has the same size as your cache capacity, you will have only 1 cache set per cache(i.e. a fully associative cache) and this **conflict miss** issue is completely gone. You will definitely get 100% hit rate if "the capacity of embedding cache can be larger than actual embedding footprint". But, the larger the cache set, the slower the searching process, so here is a hit rate vs cache performance trade-off. Also, if you really need to guarantee 100% hit rate when "the capacity of embedding cache can be larger than actual embedding footprint", you can use a data structure such as a hash table or even a linear array which don't depend on probability instead of a cache. Offen, this few percentages of miss rate caused by **conflict miss** issue won't have much impact on performance. If the hit rate is high enough, say 98%, we can just ignore the rest 2% missing keys and assign some default embedding vector to them and go to the rest of the inference pipeline(I think that's just what we did in HugeCTR inference @yingcanw ). The accuracy of the inference will not be affected by this 2% missing embeddings.
> 
> Hope this would help.

Appreciate for your response, thanks a lot. For my purpose of using LRU Cache, I want to use it in hugectr/sparse_operation_kit to accelerate training. I want use this to prefetch embeddings and make it update by steps.

**Comment by zehuanw** [comment] 2021-12-13 12:43
>Appreciate for your response, thanks a lot. For my purpose of using LRU Cache, I want to use it in hugectr/sparse_operation_kit to accelerate training. I want use this to prefetch embeddings and make it update by steps.

Our gpu cache is read only now and doesn't support writing back to CPU memory. Are you expecting some feature like this? https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/hugectr_embedding_training_cache.md

**Closed** 2022-01-24 00:56 UTC
Labels: question
