### ISSUE TITLE
[BUG] Build HugeCTR from Source ,  meet fatal error: cudf/column/column.hpp: No such file or directory

### ISSUE THREAD

**Issue by offbye** [NVIDIA-Merlin/HugeCTR#275] opened 2021-11-22 11:14 UTC
**Describe the bug**

Build HugeCTR from Source , make  errors :
data_generator.hpp:27:10: fatal error: cudf/column/column.hpp: No such file or directory
hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>

But I  have installed cudf and rmm use conda . and confirmed the install is ok.   
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> import cudf
>>>
>>> import rmm
```

**To Reproduce**
 conda install -c nvidia -c rapidsai -c conda-forge      rmm cudatoolkit=11.2
Collecting package metadata (current_repodata.json): done
Solving environment: done

 All requested packages already installed.
$  conda create -n rapids-21.10 -c rapidsai -c nvidia -c conda-forge     rapids=21.10 python=3.8 cudatoolkit=11.2
$ conda activate rapids-21.10
$ conda install -c nvidia -c rapidsai -c conda-forge     rmm cudatoolkit=11.2
   $ mkdir -p build && cd build
   $ cmake -DCMAKE_BUILD_TYPE=Release -DSM=70 .. #  ubuntu 20.04  single  V100  card
(rapids-21.10) user@myhost :~/hugectr$ make -j
[  0%] Built target copy_python
[  1%] Building CXX object tools/criteo_script_legacy/CMakeFiles/criteo2hugectr_legacy.dir/criteo2hugectr_legacy.cpp.o
[  1%] Building CXX object tools/criteo_script/CMakeFiles/criteo2hugectr.dir/criteo2hugectr.cpp.o
[  1%] Built target criteo2raw
[  1%] Building CUDA object tools/dlrm_script/CMakeFiles/dlrm_raw.dir/dlrm_raw.cu.o
[  1%] Built target gtest
[  2%] Built target gpu_cache
Consolidate compiler generated dependencies of target gmock
Consolidate compiler generated dependencies of target cache_op_sol_test
Consolidate compiler generated dependencies of target gtest_main
[  2%] Built target cache_op_sol_test
[  3%] Built target gtest_main
[  4%] Built target gmock
Consolidate compiler generated dependencies of target huge_ctr_static
[  4%] Building CXX object third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
Consolidate compiler generated dependencies of target huge_ctr_shared
[  4%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/create_embedding_cpu.cpp.o
[  4%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/create_network_cpu.cpp.o
[  5%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/create_embedding_cpu.cpp.o
[  5%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/create_network_cpu.cpp.o
[  5%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/layers/dropout_layer_cpu.cpp.o
[  6%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/network_cpu.cpp.o
[  6%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/create_pipeline_cpu.cpp.o
[  6%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/session_inference_cpu.cpp.o
[  6%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/create_pipeline_cpu.cpp.o
In file included from /home/t3mgr/hugectr/tools/criteo_script_legacy/criteo2hugectr_legacy.cpp:25:
/home/t3mgr/hugectr/HugeCTR/include/data_generator.hpp:27:10: fatal error: cudf/column/column.hpp: No such file or directory
   27 | #include <cudf/column/column.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tools/criteo_script_legacy/CMakeFiles/criteo2hugectr_legacy.dir/build.make:76: tools/criteo_script_legacy/CMakeFiles/criteo2hugectr_legacy.dir/criteo2hugectr_legacy.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2118: tools/criteo_script_legacy/CMakeFiles/criteo2hugectr_legacy.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_generator.cpp.o
In file included from /home/t3mgr/hugectr/tools/criteo_script/criteo2hugectr.cpp:26:
/home/t3mgr/hugectr/HugeCTR/include/data_generator.hpp:27:10: fatal error: cudf/column/column.hpp: No such file or directory
   27 | #include <cudf/column/column.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[  6%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/layers/dropout_layer_cpu.cpp.o
make[2]: *** [tools/criteo_script/CMakeFiles/criteo2hugectr.dir/build.make:76: tools/criteo_script/CMakeFiles/criteo2hugectr.dir/criteo2hugectr.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2066: tools/criteo_script/CMakeFiles/criteo2hugectr.dir/all] Error 2
[  6%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/network_cpu.cpp.o
[  7%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/session_inference_cpu.cpp.o
[  7%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/async_reader/async_reader.cpp.o
[  7%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/async_reader/async_reader_adapter.cpp.o
[  7%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/async_reader/thread_async_reader.cpp.o
[  7%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_generator.cpp.o
[  7%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/async_reader/async_reader.cpp.o
[  8%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/async_reader/async_reader_adapter.cpp.o
In file included from /home/t3mgr/hugectr/HugeCTR/src/cpu/layers/dropout_layer_cpu.cpp:22:
/home/t3mgr/hugectr/HugeCTR/include/data_generator.hpp:27:10: fatal error: cudf/column/column.hpp: No such file or directory
   27 | #include <cudf/column/column.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[  8%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/data_collector.cu.o
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:286: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/layers/dropout_layer_cpu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  8%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/parquet_data_converter.cu.o
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/network_cpu.hpp:24,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/create_network_cpu.cpp:37:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:174: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/create_network_cpu.cpp.o] Error 1
[  8%] Building CXX object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/async_reader/thread_async_reader.cpp.o
[  8%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/data_collector.cu.o
[  8%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/parquet_data_converter.cu.o
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/create_embedding_cpu.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/create_embedding_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:160: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/create_embedding_cpu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  8%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/embeddings/all2all_backward_functor.cu.o
[  9%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/embeddings/all2all_forward_functor.cu.o
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/create_embedding_cpu.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/create_embedding_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/t3mgr/hugectr/tools/dlrm_script/dlrm_raw.cu:19:
/home/t3mgr/hugectr/tools/dlrm_script/dlrm_raw_utils.h:28:10: fatal error: cudf/column/column.hpp: No such file or directory
   28 | #include <cudf/column/column.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tools/dlrm_script/CMakeFiles/dlrm_raw.dir/build.make:90: tools/dlrm_script/CMakeFiles/dlrm_raw.dir/dlrm_raw.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2144: tools/dlrm_script/CMakeFiles/dlrm_raw.dir/all] Error 2
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:160: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/create_embedding_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/network_cpu.hpp:24,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/create_pipeline_cpu.hpp:18,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/session_inference_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:496: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/session_inference_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/create_embedding_cpu.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/create_pipeline_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:188: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/create_pipeline_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_generator.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/data_generator.hpp:27:10: fatal error: cudf/column/column.hpp: No such file or directory
   27 | #include <cudf/column/column.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:524: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_generator.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/network_cpu.hpp:24,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/create_pipeline_cpu.hpp:18,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/session_inference_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:496: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/session_inference_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/cpu/layers/dropout_layer_cpu.cpp:22:
/home/t3mgr/hugectr/HugeCTR/include/data_generator.hpp:27:10: fatal error: cudf/column/column.hpp: No such file or directory
   27 | #include <cudf/column/column.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:286: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/layers/dropout_layer_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_generator.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/data_generator.hpp:27:10: fatal error: cudf/column/column.hpp: No such file or directory
   27 | #include <cudf/column/column.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:524: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_generator.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_readers/async_reader/thread_async_reader.cpp:15:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:594: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/async_reader/thread_async_reader.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_readers/async_reader/async_reader.cpp:16:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:538: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/async_reader/async_reader.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_readers/async_reader/async_reader_adapter.cpp:7:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:552: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/async_reader/async_reader_adapter.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/network_cpu.hpp:24,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/create_network_cpu.cpp:37:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:174: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/create_network_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_readers/async_reader/thread_async_reader.cpp:15:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:594: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/async_reader/thread_async_reader.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/create_embedding_cpu.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/create_pipeline_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_readers/async_reader/async_reader_adapter.cpp:7:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:188: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/create_pipeline_cpu.cpp.o] Error 1
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:552: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/async_reader/async_reader_adapter.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/src/data_readers/async_reader/async_reader.cpp:16:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:538: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/async_reader/async_reader.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/network_cpu.hpp:24,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/network_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:482: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/cpu/network_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_reader.hpp:23,
                 from /home/t3mgr/hugectr/HugeCTR/include/parser.hpp:19,
                 from /home/t3mgr/hugectr/HugeCTR/include/cpu/network_cpu.hpp:24,
                 from /home/t3mgr/hugectr/HugeCTR/src/cpu/network_cpu.cpp:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:482: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/cpu/network_cpu.cpp.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/embeddings/sparse_embedding_functors.hpp:20,
                 from /home/t3mgr/hugectr/HugeCTR/src/embeddings/all2all_backward_functor.cu:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:678: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/embeddings/all2all_backward_functor.cu.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/src/data_readers/data_collector.cu:18:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:608: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/data_collector.cu.o] Error 1
In file included from /home/t3mgr/hugectr/HugeCTR/include/embeddings/sparse_embedding_functors.hpp:20,
                 from /home/t3mgr/hugectr/HugeCTR/src/embeddings/all2all_forward_functor.cu:17:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/t3mgr/hugectr/HugeCTR/src/data_readers/parquet_data_converter.cu:22:10: fatal error: rmm/device_buffer.hpp: No such file or directory
   22 | #include <rmm/device_buffer.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:692: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/embeddings/all2all_forward_functor.cu.o] Error 1
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:636: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/data_readers/parquet_data_converter.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1473: HugeCTR/src/CMakeFiles/huge_ctr_static.dir/all] Error 2
/home/t3mgr/hugectr/HugeCTR/src/data_readers/parquet_data_converter.cu:22:10: fatal error: rmm/device_buffer.hpp: No such file or directory
   22 | #include <rmm/device_buffer.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/t3mgr/hugectr/HugeCTR/include/data_readers/data_collector.hpp:26,
                 from /home/t3mgr/hugectr/HugeCTR/src/data_readers/data_collector.cu:18:
/home/t3mgr/hugectr/HugeCTR/include/resource_manager.hpp:24:10: fatal error: rmm/mr/device/device_memory_resource.hpp: No such file or directory
   24 | #include <rmm/mr/device/device_memory_resource.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:636: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/parquet_data_converter.cu.o] Error 1
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/build.make:608: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/data_readers/data_collector.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1447: HugeCTR/src/CMakeFiles/huge_ctr_shared.dir/all] Error 2
[  9%] Linking CXX static library ../../../lib/libgmock_main.a
[  9%] Built target gmock_main
make: *** [Makefile:136: all] Error 2

**Expected behavior**
make  -j   succeed

**Screenshots**

**Environment (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Graphic card:  a single NVIDIA V100  
 - CUDA version:   CUDA 11.2
 - Docker image

**Additional context**
 I  have pulled the master code  in commit 638b90205529fdbd665e1d35b74f6d8fc5564b06

**Comment by XiaoleiShi-NV** [comment] 2021-12-01 04:36
Following the same procedure, I can't reproduce the listed error, probably due to the env difference.

It's may because the paths of `cudf` and `rmm` are not properly set in your environment variable.

Please check `CPATH`, `PATH` to see whether the paths of these headers can be found, so does the libraries.

---
It's recommended to build HugeCTR within the container, otherwise, unexpected errors may occur.

Check https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-training for the official container.

**Comment by zehuanw** [comment] 2021-12-13 12:44
Hi @offbye , have you solved your problem? THX!

**Comment by zehuanw** [comment] 2022-05-02 02:23
Hi @offbye  Please find the fix on Merlin here: https://github.com/NVIDIA-Merlin/HugeCTR/issues/275
I'd like to close this issue. If you still encounter it please reopen it. Thank you for your feedback again!

**Closed by zehuanw** 2022-05-02 02:23 UTC
