### ISSUE TITLE
[Question]what is about Segmentation fault when i train dlrm in mlperf?

### ISSUE THREAD

**Issue by LucQueen** [NVIDIA-Merlin/HugeCTR#372] opened 2023-01-17 09:54 UTC
I am train dlrm in mlperf, and i meet a segmentation fault below, what is the error mean, and how can i debug it ? thandks very much

```[0.00, init_start, ]
HugeCTR Version: 3.1.0
Config file: dgx_a100.json
[17d09h27m00s][HUGECTR][INFO]: Mixed Precision training with scaler: 1024 is enabled.

[17d09h27m00s][HUGECTR][INFO]: enable_tf32_compute is not specified using default: 0
[17d09h27m00s][HUGECTR][INFO]: TF32 Compute: OFF
[17d09h27m00s][HUGECTR][INFO]: algorithm_search is not specified using default: 1
[17d09h27m00s][HUGECTR][INFO]: Algorithm search: ON
[17d09h27m00s][HUGECTR][INFO]: cuda_graph is not specified using default: 1
[17d09h27m00s][HUGECTR][INFO]: CUDA Graph: ON
[17d09h27m00s][HUGECTR][INFO]: Overlapped pipeline: ON
[17d09h27m00s][HUGECTR][INFO]: Holistic CUDA Graph: ON
[17d09h27m00s][HUGECTR][INFO]: Global seed is 72258734
[17d09h27m00s][HUGECTR][INFO]: Device to NUMA mapping:
  GPU 0 ->  node 0
  GPU 1 ->  node 0
  GPU 2 ->  node 0
  GPU 3 ->  node 0
  GPU 4 ->  node 1
  GPU 5 ->  node 1
  GPU 6 ->  node 1
  GPU 7 ->  node 1

[17d09h28m03s][HUGECTR][INFO]: Start all2all warmup
[17d09h28m10s][HUGECTR][INFO]: End all2all warmup
Device 0: NVIDIA A100-SXM-80GB
Device 1: NVIDIA A100-SXM-80GB
Device 2: NVIDIA A100-SXM-80GB
Device 3: NVIDIA A100-SXM-80GB
Device 4: NVIDIA A100-SXM-80GB
Device 5: NVIDIA A100-SXM-80GB
Device 6: NVIDIA A100-SXM-80GB
Device 7: NVIDIA A100-SXM-80GB
[17d09h28m10s][HUGECTR][INFO]: Using All-reduce algorithm Oneshot
[17d09h28m10s][HUGECTR][INFO]: num_iterations_statistics is not specified using default: 20
[17d09h28m10s][HUGECTR][INFO]: AsyncReader: num_threads = 32
[17d09h28m10s][HUGECTR][INFO]: AsyncReader: num_batches_per_thread = 4
[17d09h28m10s][HUGECTR][INFO]: AsyncReader: io_block_size = 552960
[17d09h28m10s][HUGECTR][INFO]: AsyncReader: io_depth = 2
[17d09h28m10s][HUGECTR][INFO]: AsyncReader: io_alignment = 512
[17d09h28m10s][HUGECTR][INFO]: AsyncReader: num_iterations_statistics = 20
[17d09h28m10s][HUGECTR][INFO]: AsyncReader: shuffle = ON
[17d09h28m13s][HUGECTR][INFO]: num_iterations_statistics is not specified using default: 20
[17d09h28m13s][HUGECTR][INFO]: max_num_infrequent_samples is not specified using default: -1
[17d09h28m13s][HUGECTR][INFO]: p_dup_max is not specified using default: 0.010000
[17d09h28m13s][HUGECTR][INFO]: max_all_reduce_bandwidth is not specified using default: 130000000000.000000
[17d09h28m13s][HUGECTR][INFO]: max_all_to_all_bandwidth is not specified using default: 190000000000.000000
[17d09h28m13s][HUGECTR][INFO]: efficiency_bandwidth_ratio is not specified using default: 1.000000
[17d09h28m13s][HUGECTR][INFO]: Using Hybrid Embedding with train batch 55296 and eval batch 1769472
[17d09h28m44s][HUGECTR][INFO]: Starting AUC NCCL warm-up
[17d09h28m44s][HUGECTR][INFO]: Warm-up done
[104647.41, init_end, ]
[104647.43, run_start, ]
[17d09h28m46s][HUGECTR][INFO]: Initialized hybrid model with 40792 frequent categories, probability of being frequent is 0.944582
[17d09h28m46s][HUGECTR][INFO]: Estimated number of infrequent categories per train batch: 79673, eval batch:  2549563
HugeCTR training start:
[105960.99, train_epoch_start, 0, ]
[17d09h28m54s][HUGECTR][INFO]: Iter: 1000 Time(1000 iters): 8.274640s Loss: 0.822443
[17d09h28m55s][HUGECTR][INFO]: Iter: 2000 Time(1000 iters): 1.487241s Loss: 2.139164
[17d09h28m57s][HUGECTR][INFO]: Iter: 3000 Time(1000 iters): 1.487294s Loss: 2.990816
[118384.05, eval_start, 0.0499947, ]
[1673947738.699701] [9e379b1f2389:1615 :0]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 4 was not set in ucs
[9e379b1f2389:1615 :0:1623] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[1673947738.699719] [9e379b1f2389:1615 :1]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 1 was not set in ucs
[1673947738.699725] [9e379b1f2389:1615 :0]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[9e379b1f2389:1615 :1:1736] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x18)
[1673947738.699740] [9e379b1f2389:1615 :1]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1673947738.699735] [9e379b1f2389:1615 :2]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 4 was not set in ucs
[9e379b1f2389:1615 :2:1735] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10)
[1673947738.699778] [9e379b1f2389:1615 :3]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 7 was not set in ucs
[1673947738.699782] [9e379b1f2389:1615 :2]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[9e379b1f2389:1615 :3:1734] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
[1673947738.699795] [9e379b1f2389:1615 :4]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 11 was not set in ucs
[9e379b1f2389:1615 :4:1739] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x30)
[1673947738.699799] [9e379b1f2389:1615 :3]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1673947738.699815] [9e379b1f2389:1615 :5]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 1 was not set in ucs
[1673947738.699819] [9e379b1f2389:1615 :4]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[9e379b1f2389:1615 :5:1737] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x20)
[1673947738.699859] [9e379b1f2389:1615 :5]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1673947738.699854] [9e379b1f2389:1615 :6]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 4 was not set in ucs
[9e379b1f2389:1615 :6:1738] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x28)
[1673947738.699873] [9e379b1f2389:1615 :7]           debug.c:1290 UCX  WARN  ucs_debug_disable_signal: signal 1 was not set in ucs
[9e379b1f2389:1615 :7:1740] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x38)
[1673947738.699876] [9e379b1f2389:1615 :6]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
==== backtrace (tid:   1738) ====
 0  /opt/conda/lib/libucs.so.0(ucs_handle_error+0x155) [0x7f859ef607b5]
 1  /opt/conda/lib/libucs.so.0(+0x2db51) [0x7f859ef60b51]
 2  /opt/conda/lib/libucs.so.0(+0x2dd22) [0x7f859ef60d22]
 3  huge_ctr(+0x21ea6a) [0x557f7d4c1a6a]
 4  /opt/conda/lib/libgomp.so.1(+0x1d406) [0x7f85cc5f4406]
 5  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f85cd221609]
 6  /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f85cc4ed293]
=================================
[9e379b1f2389:01615] *** Process received signal ***
[9e379b1f2389:01615] Signal: Segmentation fault (11)
[9e379b1f2389:01615] Signal code:  (-6)
[9e379b1f2389:01615] Failing at address: 0x64f
[9e379b1f2389:01615] [ 0] ==== backtrace (tid:   1623) ====
 0  /opt/conda/lib/libucs.so.0(ucs_handle_error+0x155) [0x7f859ef607b5]
 1  /opt/conda/lib/libucs.so.0(+0x2db51) [0x7f859ef60b51]
 2  /opt/conda/lib/libucs.so.0(+0x2dd22) [0x7f859ef60d22]
 3  huge_ctr(+0x21ea6a) [0x557f7d4c1a6a]
 4  /opt/conda/lib/libgomp.so.1(GOMP_parallel+0x46) [0x7f85cc5ebc46]
 5  huge_ctr(+0x21b340) [0x557f7d4be340]
 6  huge_ctr(+0x21aff4) [0x557f7d4bdff4]
 7  huge_ctr(+0x104963) [0x557f7d3a7963]
 8  huge_ctr(+0xbb60a) [0x557f7d35e60a]
 9  huge_ctr(+0xbd233) [0x557f7d360233]
10  huge_ctr(+0xc035f) [0x557f7d36335f]
11  /opt/conda/lib/libstdc++.so.6(+0xdbbf4) [0x7f85cc845bf4]
12  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f85cd221609]
13  /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f85cc4ed293]
=================================
==== backtrace (tid:   1735) ====
 0  /opt/conda/lib/libucs.so.0(ucs_handle_error+0x155) [0x7f859ef607b5]
 1  /opt/conda/lib/libucs.so.0(+0x2db51) [0x7f859ef60b51]
 2  /opt/conda/lib/libucs.so.0(+0x2dd22) [0x7f859ef60d22]
 3  huge_ctr(+0x21ea6a) [0x557f7d4c1a6a]
 4  /opt/conda/lib/libgomp.so.1(+0x1d406) [0x7f85cc5f4406]
 5  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f85cd221609]
 6  /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f85cc4ed293]
=================================
Segmentation fault (core dumped)```

**Comment by kanghui0204** [comment] 2023-01-18 05:01
Hi @LucQueen ，could you send me your task script and your environment(physical machine ,NIC type ,GPU type , and gpu runtime version)?

**Comment by LucQueen** [comment] 2023-01-18 06:53
thanks，are these info below is enough？ or can you tell how to get the info you needed？because i dont know how to get NIC type :)

```root@9e379b1f2389:/workspace/dlrm# nvidia-smi
Wed Jan 18 06:35:49 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:54:00.0 Off |                    0 |
| N/A   39C    P0    88W / 400W |  69220MiB / 81251MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:5A:00.0 Off |                    0 |
| N/A   36C    P0    88W / 400W |   3005MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  Off  | 00000000:6B:00.0 Off |                    0 |
| N/A   37C    P0    90W / 400W |  69768MiB / 81251MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  Off  | 00000000:70:00.0 Off |                    0 |
| N/A   40C    P0    89W / 400W |  69336MiB / 81251MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  Off  | 00000000:BE:00.0 Off |                    0 |
| N/A   42C    P0    88W / 400W |  73514MiB / 81251MiB |      2%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  Off  | 00000000:C3:00.0 Off |                    0 |
| N/A   36C    P0    85W / 400W |    125MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  Off  | 00000000:DA:00.0 Off |                    0 |
| N/A   35C    P0    81W / 400W |      3MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  Off  | 00000000:E0:00.0 Off |                    0 |
| N/A   38C    P0    86W / 400W |      3MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+```

```nvidia-smi topo -m
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	NV12	NV12	NV12	NV12	NV12	NV12	0-31,64-95	0
GPU1	NV12	 X 	NV12	NV12	NV12	NV12	NV12	NV12	0-31,64-95	0
GPU2	NV12	NV12	 X 	NV12	NV12	NV12	NV12	NV12	0-31,64-95	0
GPU3	NV12	NV12	NV12	 X 	NV12	NV12	NV12	NV12	0-31,64-95	0
GPU4	NV12	NV12	NV12	NV12	 X 	NV12	NV12	NV12	32-63,96-127	1
GPU5	NV12	NV12	NV12	NV12	NV12	 X 	NV12	NV12	32-63,96-127	1
GPU6	NV12	NV12	NV12	NV12	NV12	NV12	 X 	NV12	32-63,96-127	1
GPU7	NV12	NV12	NV12	NV12	NV12	NV12	NV12	 X 	32-63,96-127	1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks```

**Comment by LucQueen** [comment] 2023-01-31 08:58
@kanghui0204 thanks～ I used docker base image ncg 21.05 follwing this dockerfile in github :https://github.com/mlcommons/training_results_v1.0/blob/master/NVIDIA/benchmarks/dlrm/implementations/hugectr/Dockerfile

**Comment by kanghui0204** [comment] 2023-02-01 02:02
OK , I will try to reproduce the problem. And do you mind to try our newest mlperf test? the test tutorial is: https://github.com/NVIDIA-Merlin/HugeCTR/tree/main/samples/dlrm

**Comment by kanghui0204** [comment] 2023-02-21 13:25
Hi @LucQueen ，sorry reply you later, actually I try to reproduce this problem in our environment, but I can't reproduce the preblem, I also ask our mlperf developer , he also had no idea with this error . So I recommend you to use newest mlperf in our repo. And I will close this issue, if your still have question , you can reopen it.  FYI @minseokl

**Closed by kanghui0204** 2023-02-21 13:25 UTC
Labels: question
