### ISSUE TITLE
Why my AUC is so high in first 1000 iters?

### ISSUE THREAD

**Issue by zorrofox** [NVIDIA-Merlin/HugeCTR#54] opened 2020-11-04 15:12 UTC
I just want to run a DCN sample training, and use following model JSON
```json
{
  "solver": {
    "lr_policy": "fixed",
    "display": 1000,
    "max_iter": 10000,
    "gpu": [0],
    "batchsize": 512,
    "snapshot": 10000000,
    "snapshot_prefix": "./",
    "eval_interval": 1000,
    "eval_batches": 60,
    "input_key_type": "I64"
  },
  
  "optimizer": {
    "type": "Adam",
    "global_update": true,
    "adam_hparam": {
      "learning_rate": 0.001,
      "beta1": 0.9,
      "beta2": 0.999,
      "epsilon": 0.0000001
    }
  },

  "layers": [ 
      {
      "name": "data",
      "type": "Data",
      "format": "Parquet",
      "slot_size_array": [1461, 558, 335378, 211710, 306, 20, 12136, 634, 4, 51298, 5302, 332600, 3179, 27, 12191, 301211, 11, 4841, 2086, 4, 324273, 17, 16, 79734, 96, 58622],
      "source": "./dcn_data/train/_file_list.txt",
      "eval_source": "./dcn_data/val/_file_list.txt",
      "check": "None",
      "label": {
        "top": "label",
        "label_dim": 1
      },
      "dense": {
        "top": "dense",
        "dense_dim": 13
      },
      "sparse": [
        {
          "top": "data1",
          "type": "DistributedSlot",
          "max_feature_num_per_sample": 30,
          "slot_num": 26
        }        
      ]
    },

    {
      "name": "sparse_embedding1",
      "type": "DistributedSlotSparseEmbeddingHash",
      "bottom": "data1",
      "top": "sparse_embedding1",
      "sparse_embedding_hparam": {
        "max_vocabulary_size_per_gpu": 1737709,
        "embedding_vec_size": 16,
        "combiner": 0
      }
    },

    {
      "name": "reshape1",
      "type": "Reshape",
      "bottom": "sparse_embedding1",
      "top": "reshape1",
      "leading_dim": 416
    },


    {
      "name": "concat1",
      "type": "Concat",
      "bottom": ["reshape1","dense"],
      "top": "concat1"
    },

    {
      "name": "slice1",
      "type": "Slice",
      "bottom": "concat1",
      "ranges": [[0,429], [0,429]],
      "top": ["slice11", "slice12"]
    },


    {
      "name": "multicross1",
      "type": "MultiCross",
      "bottom": "slice11",
      "top": "multicross1",
      "mc_param": {
        "num_layers": 6
      }
    },

    {
      "name": "fc1",
      "type": "InnerProduct",
      "bottom": "slice12",
      "top": "fc1",
       "fc_param": {
        "num_output": 1024
      }
    },

    {
      "name": "relu1",
      "type": "ReLU",
      "bottom": "fc1",
      "top": "relu1" 
    },
      
    {
      "name": "dropout1",
      "type": "Dropout",
      "rate": 0.5,
      "bottom": "relu1",
      "top": "dropout1" 
    },

    {
      "name": "fc2",
      "type": "InnerProduct",
      "bottom": "dropout1",
      "top": "fc2",
       "fc_param": {
        "num_output": 1024
      }
    },

    {
      "name": "relu2",
      "type": "ReLU",
      "bottom": "fc2",
      "top": "relu2"     
    },

    {
      "name": "dropout2",
      "type": "Dropout",
      "rate": 0.5,
      "bottom": "relu2",
      "top": "dropout2" 
    },
    
    {
      "name": "concat2",
      "type": "Concat",
      "bottom": ["dropout2","multicross1"],
      "top": "concat2"
    },
    
    {
      "name": "fc4",
      "type": "InnerProduct",
      "bottom": "concat2",
      "top": "fc4",
       "fc_param": {
        "num_output": 1
      }
    },
    
    {
      "name": "loss",
      "type": "BinaryCrossEntropyLoss",
      "bottom": ["fc4","label"],
      "top": "loss"
    } 
  ]
}
```

But my first 1000 iters metrics report is very strange:

```
[04d15h08m10s][HUGECTR][INFO]: Iter: 1000 Time(1000 iters): 6.113479s Loss: 0.527308 lr:0.001000
[8665.98, eval_start, 0.1, ]
[04d15h08m10s][HUGECTR][INFO]: Evaluation, AUC: 0.692035
[8708.16, eval_accuracy, 0.692035, 0.1, 1000, ]
[04d15h08m10s][HUGECTR][INFO]: Eval Time for 60 iters: 0.042175s
[8708.18, eval_stop, 0.1, ]
[04d15h08m16s][HUGECTR][INFO]: Iter: 2000 Time(1000 iters): 6.171510s Loss: 0.426323 lr:0.001000
[14837.7, eval_start, 0.2, ]
....
```
This is normal that my first 1000 iters AUC is hit 0.692035? And I find next many 1000 iters AUC is reducing.

**Comment by zehuanw** [comment] 2022-05-02 03:29
Hi @zorrofox, Sorry for late reply! I think it's not a bug but would you like to check if the latest sample still behave unexpected as they are updated with new interface / implementation. I would like to close it first, but please reopen if you still encounter the problem.

**Closed by zehuanw** 2022-05-02 03:29 UTC
