### ISSUE TITLE
[BUG] Unable to use MirroredStrategy with Sparse Operation Kit

### ISSUE THREAD

**Issue by drubinstein** [NVIDIA-Merlin/HugeCTR#291] opened 2022-01-20 17:30 UTC
**Describe the bug**

I'm trying to initialize a model with a tf.keras.Input layer being directly fed to an instance of `sok.embeddings.all2all_dense_embedding.All2AllDenseEmbedding` while using tensorflow's mirroredstrategy. When I try to call the embedding layer however, I get the following error:

```
    embeddings = embedding(inputs)
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /usr/local/lib/python3.8/dist-packages/SparseOperationKit-1.1.0-py3.8-linux-x86_64.egg/sparse_operation_kit/embeddings/all2all_dense_embedding.py:132 call  *
        emb_vector = embedding_ops.embedding_lookup(embedding_variable=self.var,
    /usr/local/lib/python3.8/dist-packages/SparseOperationKit-1.1.0-py3.8-linux-x86_64.egg/sparse_operation_kit/embeddings/embedding_ops.py:86 embedding_lookup  *
        embedding_layer = embedding_variable.embedding_layer
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/values.py:280 __getattr__
        return getattr(self._get(), name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/values.py:741 _get
        return self._get_cross_replica()
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/values.py:909 _get_cross_replica
        return self._policy._get_cross_replica(self)  # pylint: disable=protected-access

    AttributeError: 'VariableSynchronization' object has no attribute '_get_cross_replica'
```

I initialize the layer with the arguments `max_vocabulary_size_per_gpu=int(.75 * global_vocabulary_size)`, `slot_num=1` and ` nnz_per_slot=1`.

Is there anything else I need to do to call this layer while creating my tf model?

**To Reproduce/Environment**
This is on a GCP VM with 2 V100s. I've tried to run this both in the `nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.01` and `nvcr.io/nvidia/merlin/merlin-tensorflow-training:21.11` docker images. I am installing my own packages into the container, but nothing that overwrites the already installed version of tensorflow and tensorflow-related packages.

An example command I use to spin up the image:  `docker run --rm --entrypoint bash -it -v $(pwd):$(pwd)  --gpus=all --ipc=host nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.01`

**Comment by Jianbing-D** [comment] 2022-01-21 03:59
Hi @drubinstein , could you please provide a simple code snippet? So that we can try to reproduce this issue.

**Comment by drubinstein** [comment] 2022-01-21 04:35
Sure. I hope it's okay to not share exactly what we use, but this is effectively what's getting used:

```python
# Assume that batch_size, vocab_size, output_dimension, query_size, candidate_size have been previously defined
word_index_dtype = tf.int32
with strategy.scope(): # strategy is an instance of tf.MirroredStrategy()
   sok.Init(global_batch_size=batch_size)
   # I've also tested with shape=(None,)
    query_input = tf.keras.Input(shape=(query_size,), batch_size=batch_size, dtype=word_index_dtype)
    candidate_input = tf.keras.Input(
	shape=(candidate_size,), batch_size=batch_size, dtype=word_index_dtype
    )
    candidate_embedding = sok.embeddings.all2all_dense_embedding.All2AllDenseEmbedding(
        max_vocabulary_size_per_gpu=int(.75 * vocab_size),
        embedding_vec_size=output_dimensions,
        slot_num=1,
        nnz_per_slot=1
    )
    h_candidates = candidate_embedding(candidate_input) # This is where the error happens
```

**Comment by Jianbing-D** [comment] 2022-01-21 11:34
Thanks. Will let you know if we have some progress.

**Comment by Jianbing-D** [comment] 2022-01-27 09:04
Hi @drubinstein , we've found the root cause to this issue, and we are trying to fix it. I suppose the fix will be available in the next release. 

For now, please use `subclassing from tf.keras.Model` to build your model.

**Comment by drubinstein** [comment] 2022-01-31 18:15
Hi. Thanks for the update. That seems to get us farther in the training step. Need to properly figure out some shapes in our code adaptation now.

Related question, does SOK work with keras.fit (assuming a sok optimizer) or are custom training loops required?

**Comment by zehuanw** [comment] 2022-02-01 01:01
Thank you for the question and feedback! It's great to hear your progress. As many of us are in Luna New Year vacation, we may reply to you after 6th Feb.

**Comment by zehuanw** [comment] 2022-02-07 08:02
> Related question, does SOK work with keras.fit (assuming a sok optimizer) or are custom training loops required?
This feature hasn't been supported in HugeCTR SOK, and our users need to use the lower level API as demonstrated in our notebooks in the current release. it's a good requirement and we will keep you posted.

**Comment by Jianbing-D** [comment] 2022-02-25 05:00
Hi @drubinstein , 

1. You create a dataset with `tf.data.Dataset.from_tensors(global_batch_size).take(8192)`. This dataset only contains single element, whose shape is `[global_batch_size, 10, 5]`, and `take(8192)` can only take that single element from the dataset (because there is only single element can be taken). With your code, the dataset will produce  the same `[global_batch_size, 10, 5]` at each step.   (I assume you intend to use `tf.data.Dataset.from_tensor_slices`, see [its doc](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#from_tensor_slices))
2. Cause iterate that dataset will produce the same `[global_batch_size, 10, 5]` as inputs at each step, you need another TF API (`strategy.experimental_distribute_dataset`) to help you split that whole batch data into sub-batches per each GPU.  See [its doc](https://tensorflow.google.cn/versions/r1.15/api_docs/python/tf/distribute/MirroredStrategy#experimental_distribute_dataset).
3. With the following dataset, it works well.
```python
    dataset = (
        tf.data.Dataset.from_tensors(
            (
                tf.random.uniform(
                    shape=(global_batch_size, 10, 5),
                    maxval=1024,
                    dtype=tf.int64,
                ),
                tf.zeros((global_batch_size, 1), dtype=tf.float32),
            )
        )
        .take(8192)
        .cache()
        .repeat()
    )

    dataset = strategy.experimental_distribute_dataset(dataset)

    for i, (inputs, labels) in enumerate(dataset):
        replica_loss = strategy.run(_train_step, args=(inputs, labels))
        total_loss = strategy.reduce(tf.distribute.ReduceOp.SUM, replica_loss, axis=None)
        print("[SOK INFO]: Iteration: {}, loss: {}".format(i, total_loss))
```

**Comment by Jianbing-D** [comment] 2022-03-25 01:23
Hi @drubinstein , this bug should be fixed in our latest branch, would you like to try? The latest docker image should be `nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.03`.

**Comment by zehuanw** [comment] 2022-05-02 02:15
Close this issue. Please reopen it if you still encounter the same problem @drubinstein . Thank you for your feedback again!

**Closed by zehuanw** 2022-05-02 02:15 UTC
Labels: bug
