### ISSUE TITLE
[Question] How could we inspect the embedding files to sanity-check? 

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/HugeCTR#259] opened 2021-11-03 16:11 UTC
Hi, I am training a DLRM with the latest version of HugeCTR (we are using the docker image `nvcr.io/nvidia/merlin/merlin-training:21.09`), and it should be learning an embedding table for millions of categorical values. However, when I peek into the final sparse model folder that is saved at the end of training (`0_sparse_{final_epoch_num}.model`), I see that the `emb_vector` file is only 1 megabyte large. Could you please give insight into how this may happen? When I was using Hugectr 3.0.0, this file used to be gigabytes, so something must be up. 

Also, could you give instructions on how we could open the `emb_vector`, `key`, `slot_id` files from the `0_sparse_{final_epoch_num}.model` folder locally just with Python to inspect further, if possible?

Perhaps tangential to this question, could you advise further about the value that should be put for `workspace_size_per_gpu_in_mb`? I see some instructions [here](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/QAList.md#24-how-to-set-workspace_size_per_gpu_in_mb-and-slot_size_array) and [here](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/python_interface.md#sparseembedding) saying that this is the number in megabytes that should be big enough to hold all the embedding table. So, does this mean that I should put a value like `5000` if I know already that my total embedding file should be around 5 gigabytes in the end? If I put a number bigger than 2000, my process currently runs out memory (we are using 1 V100 GPU to train at the moment). If I put a number like 500, which I know is not enough space for our embedding table, the training works, and the model seems to be learning something (but then - shouldn't the `emb_vector` file then be 500MB big and not 1MB)? 

Could you please advise? Thank you so much for your help!

**Comment by minseokl** [comment] 2021-11-04 05:11
Hi @shoyasaxa 

Please find my answers below. If you have more questions, please feel free to let us know.
(1) & (2) Apology; our model file format is rather changed. Here is some information on the files inside the folder: [link](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/python_interface.md#save_params_to_files-method). Now a trained embedding table is stored as two files (Distributed Embedding) or three files (Localized Embedding) under the directory.
  - The vector file size can be calculated by `sizeof(float) * embedding_vec_size * total_number_of_unique_keys_in_dataset`. 
  -  The key file size can be calculated by `sizeof(long long) * embedding_vec_size`. 
  - Those files are just in a simple binary format. You can read each key or vector one-by-one based on the information above.

(3) workspace_size_per_gpu_in_mb: As you describe, it is enough if you set it to **a big enough value**: let's say that **the total number of unique categorical feature values** in your training dataset is `vocabulary_size_per_gpu` whilst your embedding vector size is `embedding_vec_size`. Then `workspace_size_per_gpu_in_mb` must be a value equal to or larger than `vocabulary_size_per_gpu * embedding_vec_size`.  Here are more detailed information on it:
  - `workspace_size_per_gpu_in_mb` significantly contributes to the memory size in total. However, it is not an only factor. To understand what is happening, we also need to know the batch size (for both train and eval) you use, max_eval_batches, data reader type, embedding type, etc.
  - Even if you set it to a smaller value than your actual embedding table size, it may not crash right away. Our embedding table lookup is implemented by using a variant of RAPIDS cuDF hash table. Thus, the training would continue until the hash table becomes full.

**Comment by minseokl** [comment] 2022-05-06 08:24
Hi @shoyasaxa Could you let me know if you are still facing the OOM issue? I believe the root cause was that the previous AUC implementation was not handling some input distributions in reallocating device memory. If you think it is no issue anymore, we can close it. Thank you!

**Comment by minseokl** [comment] 2022-12-27 02:55
Let's close the issue because there is no activity for a while. I will reopen or revisit the issue if there is any related issue or discussion in the future. Thanks.

**Closed by minseokl** 2022-12-27 02:55 UTC
Labels: question, TBD
