### ISSUE TITLE
[Question] why can not use multi gpu of a example notebook

### ISSUE THREAD

**Issue by LarryZhangy** [NVIDIA-Merlin/HugeCTR#332] opened 2022-06-22 02:07 UTC
when i try Embedding Training Cache Example [https://nvidia-merlin.github.io/HugeCTR/master/notebooks/embedding_training_cache_example.html](url)

if i use multi gpu by set vvgpu to [[1,2]], i wil get error at second pass  : 

HugeCTR Version:3.6 

=====================================================Model Fit=====================================================
[HCTR][02:39:45.199][INFO][RK0][main]: Use embedding training cache mode with number of training sources: 1, number of epochs: 1
[HCTR][02:39:45.199][INFO][RK0][main]: Training batchsize: 1024, evaluation batchsize: 1024
[HCTR][02:39:45.199][INFO][RK0][main]: Evaluation interval: 1000, snapshot interval: 10000
[HCTR][02:39:45.199][INFO][RK0][main]: Dense network trainable: True
[HCTR][02:39:45.199][INFO][RK0][main]: Sparse embedding sparse_embedding1 trainable: True
[HCTR][02:39:45.199][INFO][RK0][main]: Use mixed precision: False, scaler: 1.000000, use cuda graph: True
[HCTR][02:39:45.199][INFO][RK0][main]: lr: 0.001000, warmup_steps: 1, end_lr: 0.000000
[HCTR][02:39:45.199][INFO][RK0][main]: decay_start: 0, decay_steps: 1, decay_power: 2.000000
[HCTR][02:39:45.199][INFO][RK0][main]: Evaluation source file: /hugectr/tools/etc_data/file1/file_list_test.txt
[HCTR][02:39:45.199][INFO][RK0][main]: --------------------Epoch 0, source file: /hugectr/tools/etc_data/file1/file_list.txt--------------------
[HCTR][02:39:45.199][INFO][RK0][main]: Preparing embedding table for next pass
[HCTR][02:39:45.199][DEBUG][RK0][tid #139947180812032]: file_name_ /hugectr/tools/etc_data/file1/train/gen_1.parquet file_total_rows_ 1000000
[HCTR][02:39:45.199][DEBUG][RK0][tid #139947247924992]: file_name_ /hugectr/tools/etc_data/file1/train/gen_0.parquet file_total_rows_ 1000000
[HCTR][02:40:19.743][INFO][RK0][main]: HMEM-Cache PS: Hit rate [dump]: 0 %
[HCTR][02:40:21.514][INFO][RK0][main]: HMEM-Cache PS: Hit rate [load]: 0 %
[HCTR][02:40:24.353][ERROR][RK0][main]: Runtime error: invalid argument
        cudaMemPrefetchAsync(uvm_key_per_gpu[id], key_size_in_B, ((int)-1), embedding_data_.get_local_gpu(id).get_stream()) at load_parameters(/hugectr/HugeCTR/src/embeddings/distributed_slot_sparse_embedding_hash.cu:515)
[HCTR][02:40:24.353][ERROR][RK0][main]: Runtime error: invalid argument
        cudaMemPrefetchAsync(uvm_key_per_gpu[id], key_size_in_B, ((int)-1), embedding_data_.get_local_gpu(id).get_stream()) at load_parameters(/hugectr/HugeCTR/src/embeddings/distributed_slot_sparse_embedding_hash.cu:515)
Traceback (most recent call last):
  File "etc_sample.py", line 86, in <module>
    model.fit(num_epochs = 1, display = 100, eval_interval = 1000)
RuntimeError: Runtime error: invalid argument
        cudaMemPrefetchAsync(uvm_key_per_gpu[id], key_size_in_B, ((int)-1), embedding_data_.get_local_gpu(id).get_stream()) at load_parameters(/hugectr/HugeCTR/src/embeddings/distributed_slot_sparse_embedding_hash.cu:515)

**Comment by jershi425** [comment] 2022-06-22 08:07
Hi @LarryZhangy, thank you for you feedback. I can't tell the exact problem by eyeballing so I will try to reproduce this error and get back to you later. Could you please let me know which version of Merlin container are you using? Or did you build HugeCTR by your own? Thanks.

**Comment by LarryZhangy** [comment] 2022-06-22 11:16
Hi @jershi425 , I use nvcr.io/nvidia/merlin/merlin-training:22.05.
And my docker version is 18.09 ,so,  docker run --runtime nvidia to start a container.  
My host use cuda version 11.1 , driver version is 455.

**Comment by LarryZhangy** [comment] 2022-06-29 00:37
@jershi425 Have you reproduce this error ?

**Comment by jershi425** [comment] 2022-06-29 03:28
@LarryZhangy Sorry for the late reply. Yes I have reproduced the error. This happens because of the keyset mismatch. I'll solve this issue by this release(by the end of next week) and let you know. And thank you again for this important feedback!

**Comment by jershi425** [comment] 2022-07-01 03:01
@LarryZhangy Turns out it is because the keysets were extracted in a wrong way. To quickly solve this, you can modify the line 39 of `generate_keyset.py` to `f.write(int(k).to_bytes(int_size, "little", signed=True))` and re-generate the keysets.

**Comment by LarryZhangy** [comment] 2022-07-28 06:37
@jershi425 ,
Thanks! But line 39 is just the same as you describe.
And had this bug been fixed at new version?

**Comment by jershi425** [comment] 2022-08-01 02:50
@LarryZhangy This is fixed in the new version and it should run without problem.

**Comment by LarryZhangy** [comment] 2022-08-02 02:47
@jershi425 , when i try to generate keyset for first day data of criteo 1tb, i got OOM error.

![image](https://user-images.githubusercontent.com/1331144/182280567-0f12feea-b1ae-4276-b092-a43145411858.png)

![image](https://user-images.githubusercontent.com/1331144/182280858-2b9ac749-4050-4d8e-8616-7e73d5afd1a3.png)

**Comment by JacoCheung** [comment] 2022-12-27 02:12
@LarryZhangy  Sorry for the prolonged reply. After reviewing of  current Embedding Training Cache(ETC) design, we think there're some elementary defects and decide to deprecate current ETC in the near future. We're developing more effcient and scalable ways to achieve model oversubscription. Let's wait for the new features to be released!

**Closed by JacoCheung** 2022-12-27 02:12 UTC
Labels: question
